### ISSUE TITLE
Update Launch Flow Confirmation Page

### ISSUE THREAD

**Issue by earth2travis** [yeet-haus/mvp#5]
In the Launch flow...after user contributes to a project they receive the following confirmation:

![Image](https://github.com/yeet-haus/mvp/assets/82594630/d4589c85-93e4-496e-9298-d1ac83bc1bac)

Calls to Action:

- Share on Socials: https://github.com/orgs/yeet-haus/projects/1/views/1?pane=issue&itemId=50806119
- Visit DAO: link to DAO on https://admin.daohaus.club/
- View Transaction: link to transaction on block explorer

Relates to: https://github.com/yeet-haus/mvp/issues/4

**Comment by earth2travis** [comment]
- What information do we want to provide on this view?
- What calls to action do we want to provide?

### Information

- ?

### Calls to Action

- View Transaction
- Share on Socials
- Visit DAO

**Comment by earth2travis** [comment]
![Image](https://github.com/yeet-haus/mvp/assets/522182/49401d1b-45c9-4fcb-86d9-0c2497657897)

![Image](https://github.com/yeet-haus/mvp/assets/522182/e21aa66f-1815-4d4e-ab12-da2ec2b1e1b3)

**Comment by earth2travis** [comment]
Think on this flow the most obvious next steps that a user would want to take after creating a project would be to:

1. View Project (See what the project page looks like)
2. Yeet (See what the Yeet page looks like)

Share on Socials is also important but I would assume this would be the next step after verifying the the project looks good. 

View Transaction and Visit DAO are most likely not super important at the end of this flow

**Comment by skuhlmann** [comment]
I think this is in a good spot minus the social share stuff and hot dogs
