### ISSUE TITLE
Fix Float Multiplier Errors

### ISSUE THREAD

**Issue by earth2travis** [yeet-haus/mvp#52]
In the launch flow a float in the multiplication results in a console error that prevents the transaction

![Image](https://github.com/yeet-haus/mvp/assets/522182/20cdc957-d91b-4e24-bc9e-da191a59fdcf)

**Comment by skuhlmann** [comment]
potential fix: 

this field would change to a drop down and the loot per value would update based on the min yeet input.

so you put in 1 on min yeet - loot per is a drop down with:
1
10
100
1000

you put in 6.66 on min yeet - loot per is a drop down with:
6.66
66.6
666

temp fix:
locked the multiplier
