### ISSUE TITLE
Fix White Screen of Death

### ISSUE THREAD

**Issue by skuhlmann** [yeet-haus/mvp#72]
When projects page stay open for a while the go all white. You are able to restore the page with a hard refresh.

This is the Bootle of Bourbon project on Base: [https://app.yeet.haus/#/molochv3/0x2105/0x76c6f84807a84a0652f25bab218bd0d19a59417a](https://app.yeet.haus/#/molochv3/0x2105/0x76c6f84807a84a0652f25bab218bd0d19a59417a)

![Image](https://github.com/yeet-haus/mvp/assets/522182/c93715d5-3967-4cbd-bd02-d4e1e2b4d319)

**Comment by skuhlmann** [comment]
Might be fixed?

**Comment by earth2travis** [comment]
Have left a few open for a while and am not seeing the issue

Well done ser 🫡
