### ISSUE TITLE
Connect Minimum Tribute and Loot Per Minimum Tribute

### ISSUE THREAD

**Issue by earth2travis** [yeet-haus/mvp#9]
Make both Minimum Tribute and Loot Per Minimum Tribute fields editable. 

![Image](https://github.com/yeet-haus/mvp/assets/522182/099c9b49-bc2b-46c8-b735-b390820b3c02)

Could probably start with 1 ETH to 1 Loot and allow customization from there

![Image](https://github.com/yeet-haus/mvp/assets/522182/f2851e35-851b-44f2-aa3f-6f36a46c9b8e)

## Question

- Is is necessary to provide a button to reset this?

**Comment by skuhlmann** [comment]
I made both editable. I don't think it really works to connect if we want the user to be able to adjust the ratio.

I did default the loot per yeet to 100.

Feel like this is flexible and easy to use - we can adjust more later based on user feedback.
